{"uuid": "c2d7ba4a-d632-4d96-9e5a-951173ad0e0b", "children": ["2f9339de-3b01-45d1-beb5-f858e1fafd68"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities\n\n", "trace": "  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 936, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 795, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"c:\\Users\\Alex\\PycharmProjects\\Python_training\\conftest.py\", line 23, in app\n    fixture = Application(browser,target[\"web\"][\"baseUrl\"])\n  File \"c:\\Users\\Alex\\PycharmProjects\\Python_training\\fixture\\application.py\", line 14, in __init__\n    self.wd = webdriver.Firefox()\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 174, in __init__\n    keep_alive=True)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\alex\\pycharmprojects\\python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1561565519711, "stop": 1561565522757}], "start": 1561565519710, "stop": 1561565522846}